### PR TITLE
Adds a total pixel difference tolerance option

### PR DESCRIPTION
**Pull request by gstark**
This option, if specified and greater than zero, will cause the application to return a non-zero status if the total number of differing pixels is exceeded.

This can be used with `channel-tolerance`. Only pixels that exceed the `channel-tolerance` will be counted.

I am using this software in an automated way. In some cases, there are slight differences in font aliasing that I do not wish to count. However, no amount of adjusting `channel-tolerance` will cause the program to return a `0` status. In this case, I am willing to have a certain number of pixels be incorrect but still result in a `0` return.

### CODE REVIEW

**Comment by alerque** [comment]
This will be useful for me too!

That being said I will have a bit of an algorithm problem with it. When running short regression tests it will be easy to pick a tolerance value. Maybe 10 pixels. But what if the test is a 600 page document and every page has 5-10 pixel differences due to a font hinting library change? That should pass too, but it means passing a tolerance value of 6000. But now what happens if I pass a value that big and in the 600 page document almost everything is pixel perfect but one page has a small block of something that's just totally screwed up?

Would there be a way to set the tolerance as a maximum per-page or per some certain relative canvas area?

**Comment by gstark** [comment]
I thought about the same thing after I drafted this and started to try to use it. A "per page" setting would be the next most straightforward and helpful thing. Next might be setting a tolerance per page (e.g., X pixels on page 1, Y pixels on page 2, Z pixels on pages 2-20, etc.)

**Comment by gstark** [comment]
See #81 to see what a single value for a per-page setting would be like.

**Comment by vslavik** [comment]
> However, no amount of adjusting channel-tolerance will cause the program to return a 0 status.

If you mean this *literally*, i.e. even setting it to 255 has no effect, that would indicate some serious bug ...

> That being said I will have a bit of an algorithm problem with it.
...
> A "per page" setting would be the next most straightforward and helpful thing.

I do agree about this inherent problem and that per-page is better. But you're just moving the problem one level down: now the same problem arises if you change rendering resolution...

Wouldn't it be best to express the tolerance not in pixels count, but as percentage of page? Would that yield reasonable values for the parameter or would the numbers be too tiny? IOW, could you share the values you use?

**Comment by gstark** [comment]
Ah, I think I misspoke there. I meant to say that I cannot use that parameter to ignore some of the small changes in the PDFs I'm attempting to compare. I would have to set the value so close to 255 that I'm afraid of ignoring other changes.

A percentage of the page is also a good alternative.

For some example PDFS (unfortunately, I cannot share them publicly), a per-page pixel count of about 60,000 for an 8.5" x 11" page worked. In some cases it is only a few thousand pixels. There is either a slight difference in font rendering or a little difference in padding in one part of the page, causing the lower part to shift slightly in the vertical direction.

My PDFs are generated via software (HTML => PDF via [gotenberg](https://gotenberg.dev/)) and I'm trying to get that to be more consistent and avoid having _any_ pixel differences.

**Comment by vslavik** [comment]
>  a per-page pixel count of about 60,000 for an 8.5" x 11" page worked. In some cases it is only a few thousand pixels

So 0.71% or even something like 0.05% — that doesn't make it feasible UI.

> See https://github.com/vslavik/diff-pdf/pull/81 to see what a single value for a per-page setting would be like.

I think I prefer this one too - any objection to merging that one instead?

**Comment by gstark** [comment]
> > See https://github.com/vslavik/diff-pdf/pull/81 to see what a single value for a per-page setting would be like.
> 
> 
> 
> I think I prefer this one too - any objection to merging that one instead?

👍🏻

No objection! Thanks for the good discussion and consideration of the PRs.

**Comment by vslavik** [comment]
Closing in favor of #81

**Pull request closed without merging**
