### PR TITLE
correct bug when outputting a page with no differences

### PR DESCRIPTION
**Pull request by sygi**
Solving #42.

### CODE REVIEW

**Comment by vslavik** [comment]
> Solving #42.

If you don’t understand what the patch is doing and *why* it (appears to) works, that’s not “solving” — that’s shotgun debugging in its purest form. I’m not going to merge something its author has no idea how and why works, sorry.

Don’t get me wrong: I would of course be happy to merge an *explained*  change. But here, I’m actually not even sure what your *complain* is, because #42 simply asserts something is wrong, calls it “cluttered”, and shows some screenshot that doesn’t seem to have any relation to that word (I can only assume that censoring-like pixelation is what you mean, but I’m not 100% sure). But I don’t see why is it related to printing and why would it be correct to use a function meant for printing to do non-printing on-screen output.

**Comment by sygi** [comment]
Ok. Yes, your assumption was right, the problem was with the censoring-like pixelation -- the original pdf contained regular text.

It appears that indeed it is a problem with poppler:
https://sourceforge.net/p/xournal/mailman/message/34249262/
https://lists.freedesktop.org/archives/poppler/2011-December/008451.html
which falls back to some default resolution (which is very small, in my case) when you use `poppler_page_render` and doesn't when `poppler_page_render_for_printing` is used.

Cheers

**Comment by vslavik** [comment]
> It appears that indeed it is a problem with poppler:

Shouldn’t it be fixed there, then? What you provide is not an authoritative source saying we *should* do this, just another user trying the same. 

What versions of Cairo & Poppler do you use? Are they modern enough?

**Comment by sygi** [comment]
Citing from the issue description:

I have this problem on Ubuntu 14.04. with the newest libraries:
```
[master][~/projekty/diff-pdf]$ apt-show-versions libpoppler-glib-dev poppler-utils libwxgtk3.0-dev       
libpoppler-glib-dev:amd64/trusty-security 0.24.5-2ubuntu4.4 uptodate
libwxgtk3.0-dev:amd64/trusty 3.0.0-2 uptodate
poppler-utils:amd64/trusty-security 0.24.5-2ubuntu4.4 uptodate
```

Shouldn’t it be fixed there, then? – you're reading a pdf document and then saving it to the cairo_pdf_surface. Later it is (if `--output-diff` is passed), _printed_ (according to cairo/poppler definition of printing) to the file.

It seems then that rendering `for_printing` is the right thing to do for `--output-diff` and doesn't harm when you just view.

**Comment by vslavik** [comment]
> Citing the issue description:

Let that be a practical lesson on why filing duplicate issues is harmful. 

Also, your original issue didn't answer my question and neither did you now w.r.t. your *cairo* version.

> I have this problem on Ubuntu 14.04. with the newest libraries:

"Newest" really doesn't go together with a *two years old* distribution. The latest version of Poppler is 0.45 at this moment and there were *29* releases since the old version you use. I would prefer to see if this couldn't be fixed simply by bumping the required poppler version...

> Later it is (if --output-diff is passed), printed (according to cairo/poppler definition of printing) to the file.

(Authoritative) citation needed — can you please point me to where Poppler and/or Cairo docs explain this? So far I've only seen another user hypothetizing this, much like you do, but no "official" guidelines. I'm asking because...

> It seems then that rendering for_printing is the right thing to do for --output-diff and doesn't harm when you just view.

...this is overly optimistic. If it "didn't harm", there wouldn't be two versions in the first place, would there? In reality, it does harm, in potentially much increases memory usage. Your screenshot from #42 shows badly corrupted *at screen resolution*, what relation does that have to (presumably hi-res) printing? 

I'm not saying you're wrong, but I'm saying that I don't *understand* the reasoning behind this change.

**Comment by vslavik** [comment]
Closing due to submitter going incommunicado.

**Pull request closed without merging**
