### PR TITLE
Convert README to markdown

### PR DESCRIPTION
**Pull request by jbonigomes**
Great project, although very well written, I found it a little difficult to follow the documentation as it was not written in markdown, hopefully this will help.

### CODE REVIEW

**Comment by vslavik** [comment]
If well-formatted plain text is “difficult to follow” for you, you’re in for far worse clashes with reality I’m afraid… The tool is rough around the edges.

But sure, if it’s something kids these days require — thanks! But can you please fix some issues with it first, then update the PR (with `git push -f`, not messy fixup commits):

- You didn’t actually make GitHub *use* markup (as you can easily see in your own repo), because you didn’t rename the file to `README.md`...
- Please properly phrased git commit messages (“Convert”, not “Converting”).
- [Links with “here” as the text are evil](https://www.w3.org/QA/Tips/noClickHere), the plain text version was more readable in that way.
- [Some places](https://github.com/vslavik/diff-pdf/pull/47/commits/3ff6ad5aebffec2b4b15cd4451f40eadabf1b588#diff-c47c7c7383225ab55ff591cb59c41e6bR76) don’t properly backquote commands.
- Thinks like “MinGW”, “wxWidgets”, “Poppler” are proper names and should *not* be backquoted.
- Neither should the entirety of `mingw\Products\ directory` (proofreading!).

**Comment by jbonigomes** [comment]
Thanks @vslavik, very well spotted points. I have updated now the PR, also, I added a few "$" that were missing, when displaying code that should be run in the terminal.

**Comment by vslavik** [comment]
Thanks! Merged right away, then.

**Comment by jbonigomes** [comment]
Thanks

**Pull request merged**
