### PR TITLE
limit the coordinates to the Thumbnail limits

### PR DESCRIPTION
**Pull request by MichaelPFrey**

### CODE REVIEW

**Comment by vslavik** [comment]
Thanks! However, could you please add a description (preferably to the commit, but at least here) explaining *why* the change is done and what it does?

When I say "why", I mean the higher-level *purpose* or *goal* of it, not things like a low-level "limit the coordinates" comment right new to code that self-evidently limits the coordinates *for some reason*. That reason is what is unclear to me even now and what will be unclear to a future reader of the code.

It's also generally better to have [clean, well described git histories](https://chris.beams.io/posts/git-commit/), things like "clean up" commit should ideally be squashed together with the previous commit (you can `git push -f` into PRs, it's not a problem). But that's something I can do when merging if you're not very familiar with git.

I would appreciate a bit more cleanup of the patch, though, so that it respects coding conventions around it (things like a space after `=` or `//`, `if (` and not `if(`, aligning text instead of the disorderly `SetRGB` mess (would fit on a single line just fine now...) etc.). Thanks!

**Comment by MichaelPFrey** [comment]
The best kind of documentation I can think of would be a test case.
I will synthesize an example set of PDFs.

**Comment by MichaelPFrey** [comment]
assert failed
[e.PDF](https://github.com/vslavik/diff-pdf/files/1565673/e.PDF)
[f.PDF](https://github.com/vslavik/diff-pdf/files/1565674/f.PDF)

Feel free to squash all of my commits together.
Feel free to write a better comment.

This issue is a literal corner case issue. "Unfortunately" I run into that issue in the first minutes of testing diff-pdf, as the PDFs I used intentionally have only very thins white borders on the document, so the printer can print the drawings as larger as possible.

**Comment by MichaelPFrey** [comment]
Thinking harder: The real problem could be the calculation of the thumbnail height:
thumbnail_height = int(rdiff.height * thumbnail_scale);
casting to int will floor/round down the variable.
We could add an +1 there.

Or it could be a scale issue.
When we request thumbnail of 100 x 50, the highest valid coordinate is 99,49, as the first coordinate is 0,0.

On the other hand: converting/casting int to float and backward, doing float calculations - rounding errors happen.
Going one step further: What about malformed PDFs? I do not know the PDF format and the libraries used well in enough, but I can imagine that someone manages to create a PDF with lines outside the drawing area (for e.g. a letter on the edge of the paper).
Limiting the coordinates seams the most robust solution for this error class.

(unchecking "show show this dialog next time" and press continue also works by the way, but I can not tell that to my users)

**Comment by MichaelPFrey** [comment]
Test case with a text going over the edge:
[err1.pdf](https://github.com/vslavik/diff-pdf/files/1565708/err1.pdf)
[err2.pdf](https://github.com/vslavik/diff-pdf/files/1565709/err2.pdf)

I have to add: The bug only occurs, when a change is near the edge.
Geometry on the edge it self is not problem - just when there is a change near the edge we have an issue.

The test pdfs are created with Inkscape.

**Comment by MichaelPFrey** [comment]
rewrote the the comment and cleaned up the code.
Feel free to squash the changes.

**Comment by vslavik** [comment]
Merged, thanks!

**Comment by MichaelPFrey** [comment]
thank you too. I wish you a great new year.

**Pull request merged**
