### PR TITLE
Fix issues with 0.4 release

### PR DESCRIPTION
**Pull request by alxckn**
The new features are great additions.
But I believe there are a few bugs that made their way in there as well.

Those two commits fix a bug with g_channel_tolerance evaluation as well as a wrong return code.

### CODE REVIEW

**Comment by vslavik** [comment]
Thanks! I badly screwed up reviewing #62, didn't I 😬

**Comment by alxckn** [comment]
No problem, happy to help out. This software is of great help to my team by the way.

On a side note, the program seems to be crash when `--output-diff` is not specified (but I didn't investigate this issue further):

```
root@localhost:/data# diff-pdf base.pdf new.pdf 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Segmentation fault (core dumped)
```

**Comment by jlemangarin** [comment]
> This software is of great help to my team by the way.

Same here ! :)

**Comment by pietvo** [comment]
I don't know if this is related, but on MacOS I get a Segmentation fault whenever diff-pdf compares two files, not only when viewing. Only with diff-pdf --help it does not crash.

diff-pdf example1.pdf OUTPUT/example1.pdf
Segmentation fault: 11

Stack trace:

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libcairo.2.dylib              	0x000000010bf2e139 cairo_show_page + 9
1   diff-pdf                      	0x000000010ba53587 page_compare(_cairo*, _PopplerPage*, _PopplerPage*, wxImage*, int) + 215 (diff-pdf.cpp:322)
2   diff-pdf                      	0x000000010ba53854 doc_compare(_PopplerDocument*, _PopplerDocument*, char const*, std::__1::vector<bool, std::__1::allocator<bool> >*, wxProgressDialog*, Gutter*) + 628 (diff-pdf.cpp:466)
3   diff-pdf                      	0x000000010ba54bed main + 2237 (diff-pdf.cpp:986)

**Pull request merged**
