### PR TITLE
Added note about installing in Fedora and CentOS 8

### PR DESCRIPTION
**Pull request by Vascom**
Now diff-pdf available from official Fedora and EPEL 8 repo.

### CODE REVIEW

**Comment by vslavik** [comment]
Thanks, but please fix the formatting to be consistent with the rest of text (instead of adding a Fedora subheading under which OpenSUSE is then discussed).

[Better phrasing for the git commit message](https://chris.beams.io/posts/git-commit/) would be "Add note about…" too, i.e. not past tense.

**Comment by Vascom** [comment]
Can you correct it?

**Comment by vslavik** [comment]
Open Source works on giving back: you get to use something for free, in return you give back e.g. by contributing a PR (which is much appreciated!). But you can't do a half-assed or formatting-breaking PR and say "fix it after me", that's no longer giving back, but asking others to do what you want, which isn't as cool as contributing something. So if you could get this PR into a state when it can be merged yourself, that would be much appreciated. TIA!

**Comment by Vascom** [comment]
Why I can't do that? I already did it :)
Formatting corrected.

**Comment by vslavik** [comment]
Thanks!

**Pull request merged**
