### PR TITLE
Dockerfile added

### PR DESCRIPTION
**Pull request by anandtripathi5**
Docker support added

### CODE REVIEW

**Comment by vslavik** [comment]
Sorry, I don't really see the point (and the commit message doesn't explain it)...?

**Comment by anandtripathi5** [comment]
Just another way to run diff-pdf if you are on a different OS like mac m1 and having some problems `libpoppler-utils`. Docker support can be quite useful to run the diff-pdf tool like 
`docker run diff-pdf:0.5.0 <pdf-1> <pdf-2>`
Something like this. So instead of downloading all the other packages it will be quite handy to just compare with docker image.
If its fine we can also add this in `Readme.md`

**Comment by vslavik** [comment]
> Just another way to run diff-pdf if you are on a different OS like mac m1 and having some problems libpoppler-utils. 

`brew install diff-pdf` 

> Docker support can be quite useful to run the diff-pdf tool like docker run diff-pdf:0.5.0 <pdf-1> <pdf-2>

I think I'm going to pass on this, sorry. Native packaging is welcome (and as you can see in the readme, rather widespread), but this seems to be taking it a hop too far.

**Comment by vslavik** [comment]
> Any user running Linux could use the tool without the need for a whole build workflow (clone, install deps & compile)

Lot (most?) of them have diff-pdf packages...

That said, I changed my mind about the usefulness of docker images for CLI tools and would accept a PR that executes it well, i.e. also updates the README and adds GitHub Actions workflow to build the container and publish it to ghcr.io [^1].

[^1]: See e.g. commits from [here](https://github.com/vslavik/bakefile/commits/legacy-0.2-branch) for the latter, which is coincidentally where I changed my mind about this.

**Pull request closed without merging**
