### PR TITLE
Adds a per page pixel difference tolerance option

### PR DESCRIPTION
**Pull request by gstark**
This option, if specified and greater than zero will cause the application to return a non-zero status if any page has more pixel changes than the value of per-page-pixel-tolerance

This can be used with channel-tolerance. Only pixels that exceed the channel-tolerance will be counted.

### CODE REVIEW

**Comment by alerque** [comment]
Nice. I think this iteration would give my use cases a lot more utility.

**Comment by vslavik** [comment]
Merged, thanks!

**Comment by gstark** [comment]
@vslavik Would it be possible to have a new release? I use this via a [github action](https://github.com/hidakatsuya/setup-diff-pdf), and it only supports referencing a release version.

**Comment by vslavik** [comment]
> @vslavik Would it be possible to have a new release?

Sure: https://github.com/vslavik/diff-pdf/releases/tag/v0.5.1

**Comment by jeansagi** [comment]
@vslavik a huge Thanks for this utility. It has been particularly useful.

I know:

> ... _and the code is not being actively developed_ ...

But given the recent version I want to ask if anyone here could check the "**--help**" option, because on _windows_ it is not working.

The thing is that:
`pdf-diff --help`

Shows nothing onscreen.

I also tried:
`pdf-diff --h`
`pdf-diff -h`
`pdf-diff h`
`pdf-diff help`

But the same: Nothing shows onscreen.
In fact, not even errors shows onscreen ( discovered --dpi had an integer option looking inside the .exe ;) ).

So, as I said, Maybe someone could check... It should not be that hard... I presume.


J.

BTW: I'm on Windows 11 Pro (22621.1555) and I installed it with [chocolatey](https://community.chocolatey.org/packages/diff-pdf).

**Pull request merged**
