### PR TITLE
Fix warnings.

### PR DESCRIPTION
**Pull request by Vascom**
This patch fix all build warnings.

### CODE REVIEW

**Comment by vslavik** [comment]
A little more information wouldn't hurt. Please also follow [this](https://chris.beams.io/posts/git-commit/).

**Comment by Vascom** [comment]
Warnings
```
gutter.cpp:106:25: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
  106 |     if ( GetSelection() == n )
      |          ~~~~~~~~~~~~~~~^~~~
```
Next
```
diff-pdf.cpp:729:25: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<bool>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
  729 |         if ( m_cur_page < m_pages.size() - 1 )
      |              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```
Next
```
diff-pdf.cpp:740:33: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<bool>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
  740 |         event.Enable(m_cur_page < m_pages.size() - 1);
      |                      ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```
Next
```
diff-pdf.cpp:262:19: warning: 'thumbnail_height' may be used uninitialized in this function [-Wmaybe-uninitialized]
  262 |         for ( int i = thumbnail_width * thumbnail_height; i > 0; i-- )
      |                   ^
```
Full build log https://kojipkgs.fedoraproject.org//packages/diff-pdf/0.4.1/2.fc32/data/logs/x86_64/build.log

**Comment by Vascom** [comment]
Any suggestions?

**Comment by vslavik** [comment]
> Any suggestions?

One I suppose: that *fully* reading my previous comment, including the links, and acting on it wouldn't hurt. Also, please don't bug.

**Comment by vslavik** [comment]
Closing as evidently abandoned.

**Comment by Vascom** [comment]
:(

**Comment by vslavik** [comment]
> :(

I share that sentiment. I asked you to get the PR into mergeable state, with specific asks. It is clear you have no interest in doing that, so there seems to be no point in keeping this PR one, is there.

**Comment by Vascom** [comment]
I have no skills to write good PR.

My hope was that you pay attention to this warnings and my attempt fix them. And you correct me or make fix from your side as you prefer to write code.

**Comment by vslavik** [comment]
> I have no skills to write good PR.

Sorry, but that's just a lazy excuse. Explaining oneself is not hard and I linked you to extremely well-explained article on how to write commit messages. Following that requires to "skills" to speak of.

It's perfectly OK and understandable that you don't want to spend time on that. It's also perfectly fine that I don't want to spend time on a PR that doesn't meet this minimum standard.

**Pull request closed without merging**
