### PR TITLE
rasterization dpi option

### PR DESCRIPTION
**Pull request by bendablegears**
Our use case is detecting changes to computer generated pdfs. Even simple changes in the software's drawing order was causing diff-pdf to report changes that a human could not pick out by eye. With a lower dpi these changes can be smoothed out and ignored using the channel-tolerance option.

I'm on Windows and couldn't get the build dependencies resolved. If there's any problem with the pull request feel free to decline it and I'll get a Unix machine set up and properly test this.

### CODE REVIEW

**Comment by vslavik** [comment]
Thanks a lot, this does seem useful! Let's see if the builds succeeds.

Would be nice to have a best-practices git message on it (see https://chris.beams.io/posts/git-commit/)...

**Comment by bendablegears** [comment]
Commit message adjusted.

**Comment by vslavik** [comment]
You said you couldn't build on Windows above — can you check the CI build from https://ci.appveyor.com/api/buildjobs/d6rfkc8bfitrlccp/artifacts/diff-pdf-win-0.4.1.zip if it works correctly? 

If it does, I think this is so nice a a feature that it is worth making a new release just for it.

**Comment by vslavik** [comment]
One more thing: what DPI values do you use? Your experience sounds like a good argument for tweaking the defaults to be more reasonable (i.e. roughly correspond to the "a human can pick it up" threshold)...

**Comment by bendablegears** [comment]
It worked for me, with a pleasant side effect of lower dpi diffs taking less time to load up in the viewer.

For my use case, I lowered it to 96 dpi but ['experts' on the internet](https://qr.ae/pN3Ku3) seem to think that 350 dpi is the edge of perspective, at least when it comes to differentiating lines.

**Comment by vslavik** [comment]
Now released in [v0.5](https://github.com/vslavik/diff-pdf/releases/tag/v0.5).

Thanks!

**Pull request merged**
